language: node_js
node_js:
  - "6"
script: npm run test
env:
  - TRAVIS=travis CXX=g++-4.8
after_success:
  - bash <(curl -s https://codecov.io/bash)
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8