language: node_js
node_js:
  - "5.8.0"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: "./node_modules/karma/bin/karma start static/test/karma.conf.js --browsers Firefox --single-run --no-auto-watch --capture-timeout 60000"