// flow-typed signature: 4564bbe6ed474cf1a378d4253f574ddf
// flow-typed version: <<STUB>>/node-untappd_v^0.4.1/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-untappd'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-untappd' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-untappd/Example' {
  declare module.exports: any;
}

declare module 'node-untappd/Test' {
  declare module.exports: any;
}

declare module 'node-untappd/UntappdClient' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-untappd/Example.js' {
  declare module.exports: $Exports<'node-untappd/Example'>;
}
declare module 'node-untappd/Test.js' {
  declare module.exports: $Exports<'node-untappd/Test'>;
}
declare module 'node-untappd/UntappdClient.js' {
  declare module.exports: $Exports<'node-untappd/UntappdClient'>;
}
