// flow-typed signature: 40245396139bb654622e8bfd27fe89d6
// flow-typed version: <<STUB>>/react-search-input_v^0.10.4/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-search-input'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-search-input' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-search-input/lib/__tests__/getValuesForKeys.test' {
  declare module.exports: any;
}

declare module 'react-search-input/lib/__tests__/searchStrings.test' {
  declare module.exports: any;
}

declare module 'react-search-input/lib/index' {
  declare module.exports: any;
}

declare module 'react-search-input/lib/util' {
  declare module.exports: any;
}

declare module 'react-search-input/src/__tests__/getValuesForKeys.test' {
  declare module.exports: any;
}

declare module 'react-search-input/src/__tests__/searchStrings.test' {
  declare module.exports: any;
}

declare module 'react-search-input/src/index' {
  declare module.exports: any;
}

declare module 'react-search-input/src/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-search-input/lib/__tests__/getValuesForKeys.test.js' {
  declare module.exports: $Exports<'react-search-input/lib/__tests__/getValuesForKeys.test'>;
}
declare module 'react-search-input/lib/__tests__/searchStrings.test.js' {
  declare module.exports: $Exports<'react-search-input/lib/__tests__/searchStrings.test'>;
}
declare module 'react-search-input/lib/index.js' {
  declare module.exports: $Exports<'react-search-input/lib/index'>;
}
declare module 'react-search-input/lib/util.js' {
  declare module.exports: $Exports<'react-search-input/lib/util'>;
}
declare module 'react-search-input/src/__tests__/getValuesForKeys.test.js' {
  declare module.exports: $Exports<'react-search-input/src/__tests__/getValuesForKeys.test'>;
}
declare module 'react-search-input/src/__tests__/searchStrings.test.js' {
  declare module.exports: $Exports<'react-search-input/src/__tests__/searchStrings.test'>;
}
declare module 'react-search-input/src/index.js' {
  declare module.exports: $Exports<'react-search-input/src/index'>;
}
declare module 'react-search-input/src/util.js' {
  declare module.exports: $Exports<'react-search-input/src/util'>;
}
