// flow-typed signature: 9a745f0a8d1eead99741f583fc68c91f
// flow-typed version: <<STUB>>/react-google-maps_v^4.11.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-google-maps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-google-maps' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-google-maps/lib/__mocks__/google.maps.event.mock' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/__mocks__/google.maps.mock' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/__tests__/__setup__' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/__tests__/GoogleMap.spec' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/__tests__/index.spec' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/_Skeleton' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/addons/addonsCreators/InfoBoxCreator' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/addons/addonsCreators/MarkerClustererCreator' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/addons/addonsEventLists/InfoBoxEventList' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/addons/addonsEventLists/MarkerClustererEventList' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/addons/InfoBox' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/addons/MarkerClusterer' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/async/ScriptjsGoogleMap' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/async/ScriptjsLoader' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/Circle' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/creators/_SkeletonCreator' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/creators/CircleCreator' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/creators/DirectionsRendererCreator' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/creators/DrawingManagerCreator' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/creators/GoogleMapHolder' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/creators/InfoWindowCreator' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/creators/KmlLayerCreator' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/creators/MarkerCreator' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/creators/OverlayViewCreator' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/creators/PolygonCreator' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/creators/PolylineCreator' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/creators/RectangleCreator' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/creators/SearchBoxCreator' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/DirectionsRenderer' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/DrawingManager' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/eventLists/CircleEventList' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/eventLists/DirectionsRendererEventList' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/eventLists/DrawingManagerEventList' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/eventLists/GoogleMapEventList' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/eventLists/InfoWindowEventList' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/eventLists/KmlLayerEventList' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/eventLists/MarkerEventList' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/eventLists/PolygonEventList' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/eventLists/PolylineEventList' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/eventLists/RectangleEventList' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/eventLists/SearchBoxEventList' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/GoogleMap' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/GoogleMapLoader' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/index' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/InfoWindow' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/KmlLayer' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/Marker' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/OverlayView' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/Polygon' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/Polyline' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/Rectangle' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/SearchBox' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/utils/__tests__/index.spec' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/utils/addDefaultPrefix' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/utils/componentLifecycleDecorator' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/utils/composeOptions' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/utils/controlledOrDefault' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/utils/defaultPropsCreator' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/utils/eventHandlerCreator' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/utils/index' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/utils/makeUrl' {
  declare module.exports: any;
}

declare module 'react-google-maps/lib/utils/setContentForOptionalReactElement' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/__mocks__/google.maps.event.mock' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/__mocks__/google.maps.mock' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/__tests__/__setup__' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/__tests__/GoogleMap.spec' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/__tests__/index.spec' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/_Skeleton' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/addons/addonsCreators/InfoBoxCreator' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/addons/addonsCreators/MarkerClustererCreator' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/addons/addonsEventLists/InfoBoxEventList' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/addons/addonsEventLists/MarkerClustererEventList' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/addons/InfoBox' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/addons/MarkerClusterer' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/async/ScriptjsGoogleMap' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/async/ScriptjsLoader' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/Circle' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/creators/_SkeletonCreator' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/creators/CircleCreator' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/creators/DirectionsRendererCreator' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/creators/DrawingManagerCreator' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/creators/GoogleMapHolder' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/creators/InfoWindowCreator' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/creators/KmlLayerCreator' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/creators/MarkerCreator' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/creators/OverlayViewCreator' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/creators/PolygonCreator' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/creators/PolylineCreator' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/creators/RectangleCreator' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/creators/SearchBoxCreator' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/DirectionsRenderer' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/DrawingManager' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/eventLists/CircleEventList' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/eventLists/DirectionsRendererEventList' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/eventLists/DrawingManagerEventList' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/eventLists/GoogleMapEventList' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/eventLists/InfoWindowEventList' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/eventLists/KmlLayerEventList' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/eventLists/MarkerEventList' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/eventLists/PolygonEventList' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/eventLists/PolylineEventList' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/eventLists/RectangleEventList' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/eventLists/SearchBoxEventList' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/GoogleMap' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/GoogleMapLoader' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/index' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/InfoWindow' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/KmlLayer' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/Marker' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/OverlayView' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/Polygon' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/Polyline' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/Rectangle' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/SearchBox' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/utils/__tests__/index.spec' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/utils/addDefaultPrefix' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/utils/componentLifecycleDecorator' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/utils/composeOptions' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/utils/controlledOrDefault' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/utils/defaultPropsCreator' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/utils/eventHandlerCreator' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/utils/index' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/utils/makeUrl' {
  declare module.exports: any;
}

declare module 'react-google-maps/src/utils/setContentForOptionalReactElement' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-google-maps/lib/__mocks__/google.maps.event.mock.js' {
  declare module.exports: $Exports<'react-google-maps/lib/__mocks__/google.maps.event.mock'>;
}
declare module 'react-google-maps/lib/__mocks__/google.maps.mock.js' {
  declare module.exports: $Exports<'react-google-maps/lib/__mocks__/google.maps.mock'>;
}
declare module 'react-google-maps/lib/__tests__/__setup__.js' {
  declare module.exports: $Exports<'react-google-maps/lib/__tests__/__setup__'>;
}
declare module 'react-google-maps/lib/__tests__/GoogleMap.spec.js' {
  declare module.exports: $Exports<'react-google-maps/lib/__tests__/GoogleMap.spec'>;
}
declare module 'react-google-maps/lib/__tests__/index.spec.js' {
  declare module.exports: $Exports<'react-google-maps/lib/__tests__/index.spec'>;
}
declare module 'react-google-maps/lib/_Skeleton.js' {
  declare module.exports: $Exports<'react-google-maps/lib/_Skeleton'>;
}
declare module 'react-google-maps/lib/addons/addonsCreators/InfoBoxCreator.js' {
  declare module.exports: $Exports<'react-google-maps/lib/addons/addonsCreators/InfoBoxCreator'>;
}
declare module 'react-google-maps/lib/addons/addonsCreators/MarkerClustererCreator.js' {
  declare module.exports: $Exports<'react-google-maps/lib/addons/addonsCreators/MarkerClustererCreator'>;
}
declare module 'react-google-maps/lib/addons/addonsEventLists/InfoBoxEventList.js' {
  declare module.exports: $Exports<'react-google-maps/lib/addons/addonsEventLists/InfoBoxEventList'>;
}
declare module 'react-google-maps/lib/addons/addonsEventLists/MarkerClustererEventList.js' {
  declare module.exports: $Exports<'react-google-maps/lib/addons/addonsEventLists/MarkerClustererEventList'>;
}
declare module 'react-google-maps/lib/addons/InfoBox.js' {
  declare module.exports: $Exports<'react-google-maps/lib/addons/InfoBox'>;
}
declare module 'react-google-maps/lib/addons/MarkerClusterer.js' {
  declare module.exports: $Exports<'react-google-maps/lib/addons/MarkerClusterer'>;
}
declare module 'react-google-maps/lib/async/ScriptjsGoogleMap.js' {
  declare module.exports: $Exports<'react-google-maps/lib/async/ScriptjsGoogleMap'>;
}
declare module 'react-google-maps/lib/async/ScriptjsLoader.js' {
  declare module.exports: $Exports<'react-google-maps/lib/async/ScriptjsLoader'>;
}
declare module 'react-google-maps/lib/Circle.js' {
  declare module.exports: $Exports<'react-google-maps/lib/Circle'>;
}
declare module 'react-google-maps/lib/creators/_SkeletonCreator.js' {
  declare module.exports: $Exports<'react-google-maps/lib/creators/_SkeletonCreator'>;
}
declare module 'react-google-maps/lib/creators/CircleCreator.js' {
  declare module.exports: $Exports<'react-google-maps/lib/creators/CircleCreator'>;
}
declare module 'react-google-maps/lib/creators/DirectionsRendererCreator.js' {
  declare module.exports: $Exports<'react-google-maps/lib/creators/DirectionsRendererCreator'>;
}
declare module 'react-google-maps/lib/creators/DrawingManagerCreator.js' {
  declare module.exports: $Exports<'react-google-maps/lib/creators/DrawingManagerCreator'>;
}
declare module 'react-google-maps/lib/creators/GoogleMapHolder.js' {
  declare module.exports: $Exports<'react-google-maps/lib/creators/GoogleMapHolder'>;
}
declare module 'react-google-maps/lib/creators/InfoWindowCreator.js' {
  declare module.exports: $Exports<'react-google-maps/lib/creators/InfoWindowCreator'>;
}
declare module 'react-google-maps/lib/creators/KmlLayerCreator.js' {
  declare module.exports: $Exports<'react-google-maps/lib/creators/KmlLayerCreator'>;
}
declare module 'react-google-maps/lib/creators/MarkerCreator.js' {
  declare module.exports: $Exports<'react-google-maps/lib/creators/MarkerCreator'>;
}
declare module 'react-google-maps/lib/creators/OverlayViewCreator.js' {
  declare module.exports: $Exports<'react-google-maps/lib/creators/OverlayViewCreator'>;
}
declare module 'react-google-maps/lib/creators/PolygonCreator.js' {
  declare module.exports: $Exports<'react-google-maps/lib/creators/PolygonCreator'>;
}
declare module 'react-google-maps/lib/creators/PolylineCreator.js' {
  declare module.exports: $Exports<'react-google-maps/lib/creators/PolylineCreator'>;
}
declare module 'react-google-maps/lib/creators/RectangleCreator.js' {
  declare module.exports: $Exports<'react-google-maps/lib/creators/RectangleCreator'>;
}
declare module 'react-google-maps/lib/creators/SearchBoxCreator.js' {
  declare module.exports: $Exports<'react-google-maps/lib/creators/SearchBoxCreator'>;
}
declare module 'react-google-maps/lib/DirectionsRenderer.js' {
  declare module.exports: $Exports<'react-google-maps/lib/DirectionsRenderer'>;
}
declare module 'react-google-maps/lib/DrawingManager.js' {
  declare module.exports: $Exports<'react-google-maps/lib/DrawingManager'>;
}
declare module 'react-google-maps/lib/eventLists/CircleEventList.js' {
  declare module.exports: $Exports<'react-google-maps/lib/eventLists/CircleEventList'>;
}
declare module 'react-google-maps/lib/eventLists/DirectionsRendererEventList.js' {
  declare module.exports: $Exports<'react-google-maps/lib/eventLists/DirectionsRendererEventList'>;
}
declare module 'react-google-maps/lib/eventLists/DrawingManagerEventList.js' {
  declare module.exports: $Exports<'react-google-maps/lib/eventLists/DrawingManagerEventList'>;
}
declare module 'react-google-maps/lib/eventLists/GoogleMapEventList.js' {
  declare module.exports: $Exports<'react-google-maps/lib/eventLists/GoogleMapEventList'>;
}
declare module 'react-google-maps/lib/eventLists/InfoWindowEventList.js' {
  declare module.exports: $Exports<'react-google-maps/lib/eventLists/InfoWindowEventList'>;
}
declare module 'react-google-maps/lib/eventLists/KmlLayerEventList.js' {
  declare module.exports: $Exports<'react-google-maps/lib/eventLists/KmlLayerEventList'>;
}
declare module 'react-google-maps/lib/eventLists/MarkerEventList.js' {
  declare module.exports: $Exports<'react-google-maps/lib/eventLists/MarkerEventList'>;
}
declare module 'react-google-maps/lib/eventLists/PolygonEventList.js' {
  declare module.exports: $Exports<'react-google-maps/lib/eventLists/PolygonEventList'>;
}
declare module 'react-google-maps/lib/eventLists/PolylineEventList.js' {
  declare module.exports: $Exports<'react-google-maps/lib/eventLists/PolylineEventList'>;
}
declare module 'react-google-maps/lib/eventLists/RectangleEventList.js' {
  declare module.exports: $Exports<'react-google-maps/lib/eventLists/RectangleEventList'>;
}
declare module 'react-google-maps/lib/eventLists/SearchBoxEventList.js' {
  declare module.exports: $Exports<'react-google-maps/lib/eventLists/SearchBoxEventList'>;
}
declare module 'react-google-maps/lib/GoogleMap.js' {
  declare module.exports: $Exports<'react-google-maps/lib/GoogleMap'>;
}
declare module 'react-google-maps/lib/GoogleMapLoader.js' {
  declare module.exports: $Exports<'react-google-maps/lib/GoogleMapLoader'>;
}
declare module 'react-google-maps/lib/index.js' {
  declare module.exports: $Exports<'react-google-maps/lib/index'>;
}
declare module 'react-google-maps/lib/InfoWindow.js' {
  declare module.exports: $Exports<'react-google-maps/lib/InfoWindow'>;
}
declare module 'react-google-maps/lib/KmlLayer.js' {
  declare module.exports: $Exports<'react-google-maps/lib/KmlLayer'>;
}
declare module 'react-google-maps/lib/Marker.js' {
  declare module.exports: $Exports<'react-google-maps/lib/Marker'>;
}
declare module 'react-google-maps/lib/OverlayView.js' {
  declare module.exports: $Exports<'react-google-maps/lib/OverlayView'>;
}
declare module 'react-google-maps/lib/Polygon.js' {
  declare module.exports: $Exports<'react-google-maps/lib/Polygon'>;
}
declare module 'react-google-maps/lib/Polyline.js' {
  declare module.exports: $Exports<'react-google-maps/lib/Polyline'>;
}
declare module 'react-google-maps/lib/Rectangle.js' {
  declare module.exports: $Exports<'react-google-maps/lib/Rectangle'>;
}
declare module 'react-google-maps/lib/SearchBox.js' {
  declare module.exports: $Exports<'react-google-maps/lib/SearchBox'>;
}
declare module 'react-google-maps/lib/utils/__tests__/index.spec.js' {
  declare module.exports: $Exports<'react-google-maps/lib/utils/__tests__/index.spec'>;
}
declare module 'react-google-maps/lib/utils/addDefaultPrefix.js' {
  declare module.exports: $Exports<'react-google-maps/lib/utils/addDefaultPrefix'>;
}
declare module 'react-google-maps/lib/utils/componentLifecycleDecorator.js' {
  declare module.exports: $Exports<'react-google-maps/lib/utils/componentLifecycleDecorator'>;
}
declare module 'react-google-maps/lib/utils/composeOptions.js' {
  declare module.exports: $Exports<'react-google-maps/lib/utils/composeOptions'>;
}
declare module 'react-google-maps/lib/utils/controlledOrDefault.js' {
  declare module.exports: $Exports<'react-google-maps/lib/utils/controlledOrDefault'>;
}
declare module 'react-google-maps/lib/utils/defaultPropsCreator.js' {
  declare module.exports: $Exports<'react-google-maps/lib/utils/defaultPropsCreator'>;
}
declare module 'react-google-maps/lib/utils/eventHandlerCreator.js' {
  declare module.exports: $Exports<'react-google-maps/lib/utils/eventHandlerCreator'>;
}
declare module 'react-google-maps/lib/utils/index.js' {
  declare module.exports: $Exports<'react-google-maps/lib/utils/index'>;
}
declare module 'react-google-maps/lib/utils/makeUrl.js' {
  declare module.exports: $Exports<'react-google-maps/lib/utils/makeUrl'>;
}
declare module 'react-google-maps/lib/utils/setContentForOptionalReactElement.js' {
  declare module.exports: $Exports<'react-google-maps/lib/utils/setContentForOptionalReactElement'>;
}
declare module 'react-google-maps/src/__mocks__/google.maps.event.mock.js' {
  declare module.exports: $Exports<'react-google-maps/src/__mocks__/google.maps.event.mock'>;
}
declare module 'react-google-maps/src/__mocks__/google.maps.mock.js' {
  declare module.exports: $Exports<'react-google-maps/src/__mocks__/google.maps.mock'>;
}
declare module 'react-google-maps/src/__tests__/__setup__.js' {
  declare module.exports: $Exports<'react-google-maps/src/__tests__/__setup__'>;
}
declare module 'react-google-maps/src/__tests__/GoogleMap.spec.js' {
  declare module.exports: $Exports<'react-google-maps/src/__tests__/GoogleMap.spec'>;
}
declare module 'react-google-maps/src/__tests__/index.spec.js' {
  declare module.exports: $Exports<'react-google-maps/src/__tests__/index.spec'>;
}
declare module 'react-google-maps/src/_Skeleton.js' {
  declare module.exports: $Exports<'react-google-maps/src/_Skeleton'>;
}
declare module 'react-google-maps/src/addons/addonsCreators/InfoBoxCreator.js' {
  declare module.exports: $Exports<'react-google-maps/src/addons/addonsCreators/InfoBoxCreator'>;
}
declare module 'react-google-maps/src/addons/addonsCreators/MarkerClustererCreator.js' {
  declare module.exports: $Exports<'react-google-maps/src/addons/addonsCreators/MarkerClustererCreator'>;
}
declare module 'react-google-maps/src/addons/addonsEventLists/InfoBoxEventList.js' {
  declare module.exports: $Exports<'react-google-maps/src/addons/addonsEventLists/InfoBoxEventList'>;
}
declare module 'react-google-maps/src/addons/addonsEventLists/MarkerClustererEventList.js' {
  declare module.exports: $Exports<'react-google-maps/src/addons/addonsEventLists/MarkerClustererEventList'>;
}
declare module 'react-google-maps/src/addons/InfoBox.js' {
  declare module.exports: $Exports<'react-google-maps/src/addons/InfoBox'>;
}
declare module 'react-google-maps/src/addons/MarkerClusterer.js' {
  declare module.exports: $Exports<'react-google-maps/src/addons/MarkerClusterer'>;
}
declare module 'react-google-maps/src/async/ScriptjsGoogleMap.js' {
  declare module.exports: $Exports<'react-google-maps/src/async/ScriptjsGoogleMap'>;
}
declare module 'react-google-maps/src/async/ScriptjsLoader.js' {
  declare module.exports: $Exports<'react-google-maps/src/async/ScriptjsLoader'>;
}
declare module 'react-google-maps/src/Circle.js' {
  declare module.exports: $Exports<'react-google-maps/src/Circle'>;
}
declare module 'react-google-maps/src/creators/_SkeletonCreator.js' {
  declare module.exports: $Exports<'react-google-maps/src/creators/_SkeletonCreator'>;
}
declare module 'react-google-maps/src/creators/CircleCreator.js' {
  declare module.exports: $Exports<'react-google-maps/src/creators/CircleCreator'>;
}
declare module 'react-google-maps/src/creators/DirectionsRendererCreator.js' {
  declare module.exports: $Exports<'react-google-maps/src/creators/DirectionsRendererCreator'>;
}
declare module 'react-google-maps/src/creators/DrawingManagerCreator.js' {
  declare module.exports: $Exports<'react-google-maps/src/creators/DrawingManagerCreator'>;
}
declare module 'react-google-maps/src/creators/GoogleMapHolder.js' {
  declare module.exports: $Exports<'react-google-maps/src/creators/GoogleMapHolder'>;
}
declare module 'react-google-maps/src/creators/InfoWindowCreator.js' {
  declare module.exports: $Exports<'react-google-maps/src/creators/InfoWindowCreator'>;
}
declare module 'react-google-maps/src/creators/KmlLayerCreator.js' {
  declare module.exports: $Exports<'react-google-maps/src/creators/KmlLayerCreator'>;
}
declare module 'react-google-maps/src/creators/MarkerCreator.js' {
  declare module.exports: $Exports<'react-google-maps/src/creators/MarkerCreator'>;
}
declare module 'react-google-maps/src/creators/OverlayViewCreator.js' {
  declare module.exports: $Exports<'react-google-maps/src/creators/OverlayViewCreator'>;
}
declare module 'react-google-maps/src/creators/PolygonCreator.js' {
  declare module.exports: $Exports<'react-google-maps/src/creators/PolygonCreator'>;
}
declare module 'react-google-maps/src/creators/PolylineCreator.js' {
  declare module.exports: $Exports<'react-google-maps/src/creators/PolylineCreator'>;
}
declare module 'react-google-maps/src/creators/RectangleCreator.js' {
  declare module.exports: $Exports<'react-google-maps/src/creators/RectangleCreator'>;
}
declare module 'react-google-maps/src/creators/SearchBoxCreator.js' {
  declare module.exports: $Exports<'react-google-maps/src/creators/SearchBoxCreator'>;
}
declare module 'react-google-maps/src/DirectionsRenderer.js' {
  declare module.exports: $Exports<'react-google-maps/src/DirectionsRenderer'>;
}
declare module 'react-google-maps/src/DrawingManager.js' {
  declare module.exports: $Exports<'react-google-maps/src/DrawingManager'>;
}
declare module 'react-google-maps/src/eventLists/CircleEventList.js' {
  declare module.exports: $Exports<'react-google-maps/src/eventLists/CircleEventList'>;
}
declare module 'react-google-maps/src/eventLists/DirectionsRendererEventList.js' {
  declare module.exports: $Exports<'react-google-maps/src/eventLists/DirectionsRendererEventList'>;
}
declare module 'react-google-maps/src/eventLists/DrawingManagerEventList.js' {
  declare module.exports: $Exports<'react-google-maps/src/eventLists/DrawingManagerEventList'>;
}
declare module 'react-google-maps/src/eventLists/GoogleMapEventList.js' {
  declare module.exports: $Exports<'react-google-maps/src/eventLists/GoogleMapEventList'>;
}
declare module 'react-google-maps/src/eventLists/InfoWindowEventList.js' {
  declare module.exports: $Exports<'react-google-maps/src/eventLists/InfoWindowEventList'>;
}
declare module 'react-google-maps/src/eventLists/KmlLayerEventList.js' {
  declare module.exports: $Exports<'react-google-maps/src/eventLists/KmlLayerEventList'>;
}
declare module 'react-google-maps/src/eventLists/MarkerEventList.js' {
  declare module.exports: $Exports<'react-google-maps/src/eventLists/MarkerEventList'>;
}
declare module 'react-google-maps/src/eventLists/PolygonEventList.js' {
  declare module.exports: $Exports<'react-google-maps/src/eventLists/PolygonEventList'>;
}
declare module 'react-google-maps/src/eventLists/PolylineEventList.js' {
  declare module.exports: $Exports<'react-google-maps/src/eventLists/PolylineEventList'>;
}
declare module 'react-google-maps/src/eventLists/RectangleEventList.js' {
  declare module.exports: $Exports<'react-google-maps/src/eventLists/RectangleEventList'>;
}
declare module 'react-google-maps/src/eventLists/SearchBoxEventList.js' {
  declare module.exports: $Exports<'react-google-maps/src/eventLists/SearchBoxEventList'>;
}
declare module 'react-google-maps/src/GoogleMap.js' {
  declare module.exports: $Exports<'react-google-maps/src/GoogleMap'>;
}
declare module 'react-google-maps/src/GoogleMapLoader.js' {
  declare module.exports: $Exports<'react-google-maps/src/GoogleMapLoader'>;
}
declare module 'react-google-maps/src/index.js' {
  declare module.exports: $Exports<'react-google-maps/src/index'>;
}
declare module 'react-google-maps/src/InfoWindow.js' {
  declare module.exports: $Exports<'react-google-maps/src/InfoWindow'>;
}
declare module 'react-google-maps/src/KmlLayer.js' {
  declare module.exports: $Exports<'react-google-maps/src/KmlLayer'>;
}
declare module 'react-google-maps/src/Marker.js' {
  declare module.exports: $Exports<'react-google-maps/src/Marker'>;
}
declare module 'react-google-maps/src/OverlayView.js' {
  declare module.exports: $Exports<'react-google-maps/src/OverlayView'>;
}
declare module 'react-google-maps/src/Polygon.js' {
  declare module.exports: $Exports<'react-google-maps/src/Polygon'>;
}
declare module 'react-google-maps/src/Polyline.js' {
  declare module.exports: $Exports<'react-google-maps/src/Polyline'>;
}
declare module 'react-google-maps/src/Rectangle.js' {
  declare module.exports: $Exports<'react-google-maps/src/Rectangle'>;
}
declare module 'react-google-maps/src/SearchBox.js' {
  declare module.exports: $Exports<'react-google-maps/src/SearchBox'>;
}
declare module 'react-google-maps/src/utils/__tests__/index.spec.js' {
  declare module.exports: $Exports<'react-google-maps/src/utils/__tests__/index.spec'>;
}
declare module 'react-google-maps/src/utils/addDefaultPrefix.js' {
  declare module.exports: $Exports<'react-google-maps/src/utils/addDefaultPrefix'>;
}
declare module 'react-google-maps/src/utils/componentLifecycleDecorator.js' {
  declare module.exports: $Exports<'react-google-maps/src/utils/componentLifecycleDecorator'>;
}
declare module 'react-google-maps/src/utils/composeOptions.js' {
  declare module.exports: $Exports<'react-google-maps/src/utils/composeOptions'>;
}
declare module 'react-google-maps/src/utils/controlledOrDefault.js' {
  declare module.exports: $Exports<'react-google-maps/src/utils/controlledOrDefault'>;
}
declare module 'react-google-maps/src/utils/defaultPropsCreator.js' {
  declare module.exports: $Exports<'react-google-maps/src/utils/defaultPropsCreator'>;
}
declare module 'react-google-maps/src/utils/eventHandlerCreator.js' {
  declare module.exports: $Exports<'react-google-maps/src/utils/eventHandlerCreator'>;
}
declare module 'react-google-maps/src/utils/index.js' {
  declare module.exports: $Exports<'react-google-maps/src/utils/index'>;
}
declare module 'react-google-maps/src/utils/makeUrl.js' {
  declare module.exports: $Exports<'react-google-maps/src/utils/makeUrl'>;
}
declare module 'react-google-maps/src/utils/setContentForOptionalReactElement.js' {
  declare module.exports: $Exports<'react-google-maps/src/utils/setContentForOptionalReactElement'>;
}
